version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: smartrent_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SuperSecretPassword123!
      POSTGRES_DB: SmartRentDb
    ports:
      - "5433:5432"
    restart: always